version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
checks:
exclude_patterns:
  - test/**/*
  - examples/**/*
