sudo: required
language: node_js
dist: trusty
node_js:
  - '8'
branches:
  except:
    - /^pr\\..*/"=
    - "/^features\\\\..*/"
before_install:
  - git clone https://github.com/djanta/travis-npm-deploy.git ~/travis-npm-deploy
  - chmod +x ~/travis-npm-deploy/deploy.sh && chmod +x ~/travis-npm-deploy/npm/*.sh
  - bash ~/travis-npm-deploy/deploy.sh --git-config
install:
  - bash ~/travis-npm-deploy/deploy.sh --install
  - npm i --verbose
  - 'echo "repo_token: $COVERALLS_REPO_TOKEN" > "./.coveralls.yml"'
  - npm run snyk:login -- $SNYK_TOKEN
script:
  - npm test
after_script:
  - echo "Running after script"
after_success:
  - npm run snyk:monitor
  - npm run coverage
before_deploy:
  - bash ~/travis-npm-deploy/deploy.sh login --user=$NPM_USER --password=$NPM_PWD --email=$NPM_EMAIL #--scope=$NPM_SCOPE
deploy:
  - provider: script
    skip_cleanup: true
    email: "$NPM_EMAIL"
    script: "~/travis-npm-deploy/deploy.sh"
    on:
      tags: true
      repo: djanta/djantajs-compiler-rc
after_deploy:
  - bash ~/travis-npm-deploy/deploy.sh logout
notifications:
  email: false
  slack:
    rooms:
      - "$SLACK_ROOM_URL"
    on_success: always
    template:
      - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch}
        by %{author} %{result} in %{duration}
  webhooks:
    urls:
      - "$WEBHOOK_GITTER"
    on_success: change
    on_failure: always
    on_start: never
